(part "PCW1J-R24-BAD252"
    (packageRef "PCW1JR24BAD252")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
        (port "MH1" (symbPinId 4) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 5) (portName "MH2") (portType INOUT))
        (port "MH3" (symbPinId 6) (portName "MH3") (portType INOUT))
        (port "MH4" (symbPinId 7) (portName "MH4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-PCW1J-R24-BAD252")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=652-PCW1J-R24-BAD252")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "PCW1J-R24-BAD252")
    (property "Description" "Potentiometers 2.5K 20% Sq 22mm Single Turn")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/PCW1J-R24-BAD252.pdf")
    (property "symbolName1" "PCW1J-R24-BAD252")
)
